#:import navigation_screen_manager navigation_screen_manager
#:import user_creation controllers.user_creation
#:import sales_page controllers.sales_page
#:import layout controllers.layout
#:import products_page controllers.products_page
#:import wallet_page controllers.wallet_page
#:import expenses_page controllers.expenses_page
#:import statistics_page controllers.statistics_page

<MyScreenManager@NavigationScreenManager>:
    UserCreationScreen:
        id:user_creation_screen
    MainScreen:
        id:mainscreen
    LayoutScreen:
    ProductsScreen:
        id:productsscreen
    WalletScreen:
        id:walletscreen
    ExpensesScreen:
        id:expensesscreen
    StatsScreen:
        id:statsscreen



<MainScreen@Screen>:
    name: "SalesPage"

    MDNavigationLayout:

        ScreenManager:
            id: nav_screen_manager

            Screen:
                name: "sales_home"
                PrincipalScreen:
                    md_bg_color: 212/255,219/255,237/255,1

                    AppBar:
                    MDScrollView:
                        id: scroll_1
                        do_scroll_x: False
                        do_scroll_y: True

                        MDBoxLayout:
                            orientation: "vertical"
                            adaptive_height: True
                            padding: dp(10)
                            spacing: dp(10)

                            SalesPage:
                                id: salespage
                                size_hint_y: None
                                height: self.minimum_height

        Gradient:
            id:nav_drawer

<UserCreationScreen@Screen>:
    name: "user_creation"
    BoxLayout:
        orientation: "vertical"

<LayoutScreen@Screen>:
    name: "layout"
    BoxLayout:
        orientation: "vertical"
        MDTopAppBar:
            title: "Page Layout"
        MDLabel:
            text: "Contenu layout"

<ProductsScreen@Screen>:
    name: "letie"
    MDNavigationLayout:
        ScreenManager:
            id: nav_screen_manager

            Screen:
                name: "sales_home"
                PrincipalScreen:
                    md_bg_color: 212/255,219/255,237/255,1
                    AppBar:
                    MDScrollView:
                        do_scroll_x: False
                        do_scroll_y: True
                        id:scroll_2
                        MDBoxLayout:
                            orientation: "vertical"
                            adaptive_height: True
                            ProductsPage:
                                id:productspage
                                size_hint_y: None
                                height: self.minimum_height


        Gradient:
            id:nav_drawer

<WalletScreen@Screen>:
    name: "WalletPage"
    MDNavigationLayout:
        ScreenManager:
            id: nav_screen_manager

            Screen:
                name: "sales_home"
                PrincipalScreen:
                    md_bg_color:248/255,247/255,242/255,1
                    AppBar:
                    MDScrollView:
                        do_scroll_x: False
                        do_scroll_y: False
                        id:scroll_3
                        MDBoxLayout:
                            orientation: "vertical"
                            adaptive_height: True
                            WalletPage:
                                id:walletpage
                                size_hint_y: None
                                height: self.minimum_height

        Gradient:
            id:nav_drawer
<ExpensesScreen@Screen>:
    name: "ExpensesPage"
    MDNavigationLayout:
        ScreenManager:
            id: nav_screen_manager

            Screen:
                name: "sales_home"
                PrincipalScreen:
                    md_bg_color:248/255,247/255,242/255,1
                    AppBar:
                    MDScrollView:
                        do_scroll_x: False
                        do_scroll_y: False
                        id:scroll_4
                        MDBoxLayout:
                            orientation: "vertical"
                            adaptive_height: True
                            ExpensesPage:
                                id:expensespage
                                size_hint_y: None
                                height: self.minimum_height

        Gradient:
            id:nav_drawer
<StatsScreen@Screen>:
    name: "StatsPage"
    MDNavigationLayout:
        ScreenManager:
            id: nav_screen_manager

            Screen:
                name: "sales_home"
                PrincipalScreen:
                    md_bg_color:248/255,247/255,242/255,1
                    AppBar:
                    MDScrollView:
                        do_scroll_x: False
                        do_scroll_y: False
                        id:scroll_5
                        MDBoxLayout:
                            orientation: "vertical"
                            adaptive_height: True
                            StatsPage:
                                id:statsspage
                                size_hint_y: None
                                height: self.minimum_height

        Gradient:
            id:nav_drawer