
<CLabel@MDLabel>:
    halign: "left"
    font_style: "OutfitBlack"
    bold: True

<CCard@MDCard>:
    style: "elevated"
    radius: [20]
    elevation: 10

<Chead@MDListItem>:
    theme_bg_color: "Custom"
    radius:[20,20,0,0]
    spacing:dp(10)
    padding:dp(10)
    halign:"center"

<CTextField@MDTextField>:
    size_hint:.8,.1
    pos_hint: {"center_x": 0.5}
    mode: "filled"
<CBox@MDBoxLayout>:
    orientation:"vertical"
    spacing:dp(20)
    padding:dp(20)


