#:import navigation_screen_manager navigation_screen_manager
#:import user_creation controllers.user_creation
#:import sales_page controllers.sales_page
#:import layout controllers.layout
#:import products_page controllers.products_page
#:import wallet_page controllers.wallet_page
#:import expenses_page controllers.expenses_page
#:import statistics_page controllers.statistics_page

<Damn>:
    id:MainManager
    UserCreationScreen:
        id:user_creation_screen
    MDScreen:
        name:"Application"
        MDNavigationLayout:

        ScreenManager:
            id: nav_screen_manager_1

            Screen:
                name: "sales_home"
                PrincipalScreen:
                    #md_bg_color: 212/255,219/255,237/255,1
                    AppBar:
                    MyScreenManager:
                        id: nav_screen_manager_2
                        MainScreen:
                            id:mainscreen
                        LayoutScreen:
                        ProductsScreen:
                            id:productsscreen
                        WalletScreen:
                            id:walletscreen
                        ExpensesScreen:
                            id:expensesscreen
                        StatsScreen:
                            id:statsscreen

                Gradient:
                    id:nav_drawer




<MainScreen@Screen>:
    name: "SalesPage"
    MDScrollView:
        id: scroll_1
        do_scroll_x: False
        do_scroll_y: True

        MDBoxLayout:
            orientation: "vertical"
            adaptive_height: True
            padding: dp(10)
            spacing: dp(10)

            SalesPage:
                id: salespage
                size_hint_y: None
                height: self.minimum_height



<UserCreationScreen@Screen>:
    name: "user_creation"
    BoxLayout:
        orientation: "vertical"

<LayoutScreen@Screen>:
    name: "layout"
    BoxLayout:
        orientation: "vertical"
        MDTopAppBar:
            title: "Page Layout"
        MDLabel:
            text: "Contenu layout"

<ProductsScreen@Screen>:
    name: "letie"
    MDScrollView:
        do_scroll_x: False
        do_scroll_y: True
        id:scroll_2
        MDBoxLayout:
            orientation: "vertical"
            adaptive_height: True
            ProductsPage:
                id:productspage
                size_hint_y: None
                height: self.minimum_height

<WalletScreen@Screen>:
    name: "WalletPage"
    MDScrollView:
        do_scroll_x: False
        do_scroll_y: False
        id:scroll_3
        MDBoxLayout:
            orientation: "vertical"
            adaptive_height: True
            WalletPage:
                id:walletpage
                size_hint_y: None
                height: self.minimum_height

<ExpensesScreen@Screen>:
    name: "ExpensesPage"
    MDScrollView:
        do_scroll_x: False
        do_scroll_y: False
        id:scroll_4
        MDBoxLayout:
            orientation: "vertical"
            adaptive_height: True
            ExpensesPage:
                id:expensespage
                size_hint_y: None
                height: self.minimum_height
<StatsScreen@Screen>:
    name: "StatsPage"

    MDScrollView:
        do_scroll_x: False
        do_scroll_y: False
        id:scroll_5
        MDBoxLayout:
            orientation: "vertical"
            adaptive_height: True
            StatsPage:
                id:statsspage
                size_hint_y: None
                height: self.minimum_height