<ExpensesPage>
    theme_bg_color:"Custom"
    #md_bg_color:139/255,139/255,139/255,1
    size_hint_y: None
    height: self.minimum_height
    spacing:dp(20)
    padding:dp(20)
    MDBoxLayout:
        orientation:"vertical"
        adaptive_height: True
        spacing:dp(20)
        padding:dp(20)
        MDBoxLayout:
            size_hint_y: None
            height: dp(70)
            orientation: "vertical"
            spacing:dp(7)
            padding:dp(7)
            MDLabel:

                size_hint_y:0.05
                text:"filtrer par"
                font_style:"Title"
                role:"medium"
            MDBoxLayout:
                size_hint_y: None
                height: dp(70)
                spacing:dp(7)
                padding:dp(7)
                MDButton:
                    id:date_button
                    theme_bg_color:"Custom"
                    md_bg_color:171/255,219/255,227/255,1
                    radius:[15]
                    size_hint_y: None
                    on_release:
                        root.show_date_picker()
                    MDButtonText:
                        text:"Date"

                MDButton:
                    theme_bg_color:"Custom"
                    md_bg_color:171/255,219/255,227/255,1
                    radius:[15]
                    size_hint_y: None
                    on_release:
                        root.show_modal_date_picker()
                    MDButtonText:
                        text:"Période"

                MDButton:
                    theme_bg_color:"Custom"
                    md_bg_color:171/255,219/255,227/255,1
                    radius:[15]
                    size_hint_y: None
                    on_release:
                        root.show_month_picker()
                    MDButtonText:
                        text:"Mois"
                MDButton:
                    theme_bg_color:"Custom"
                    md_bg_color:171/255,219/255,227/255,1
                    radius:[15]
                    size_hint_y: None
                    on_release:
                        root.show_year_picker()
                    MDButtonText:
                        text:"Année"

        MDCard:
            size_hint_x:1
            size_hint_y: None
            height: dp(550)
            style: "elevated"
            elevation:10
            radius:[20]
            ListeDepense:
                id:listedepense
                size_hint_y: None
                height: dp(550)
                size_hint : 1,1
                on_parent:self.show_expenses()
    MDBoxLayout:
        id:expense_section_2
        orientation:"vertical"
        adaptive_height: True
        spacing:dp(20)
        padding:dp(20)
        size_hint_x:0.4

        MDCard:
            size_hint_y: None
            height: dp(50)
            style: "elevated"
            elevation:10
            radius:[20]
            theme_bg_color:"Custom"
            md_bg_color:30/255,129/255,176/255,1
            BoxLayout:
                orientation:'vertical'
                MDListItem:
                    theme_bg_color: "Custom"
                    md_bg_color: [1,1,1,1]
                    size_hint:1,None
                    height: dp(40)
                    radius:[20,20,0,0]
                    spacing:dp(10)
                    padding:dp(10)
                    pos_hint: {"y": 0.9}
                    halign:"center"
                    MDListItemLeadingIcon:
                        icon: "currency-usd"
                    MDListItemHeadlineText:
                        text:"comparaison mensuelle"
                LabelSommePortefeuille:
                    size_hint_y: None
                    height :"40dp"
                    id:labelsommeportefeuille
                    text:self.somme_portefeuille
        MDCard:
            size_hint_y: None
            height: dp(300)
            style: "elevated"
            theme_bg_color: "Custom"
            size_hint_x: 1
            md_bg_color: 168,205,230,255
            radius: [20]
            elevation: 10
            BoxLayout:
                orientation:'vertical'
                MDListItem:
                    theme_bg_color: "Custom"
                    md_bg_color: 186/255,169/255,155/255,1
                    size_hint:1,None
                    height: dp(40)
                    radius:[20,20,0,0]
                    spacing:dp(10)
                    padding:dp(10)
                    pos_hint: {"y": 0.9}
                    halign:"center"

                    MDListItemLeadingIcon:
                        icon: "sale"

                    MDListItemHeadlineText:
                        text: "Pourcentage des depenses"
                PourcentageDepense:
                    id:pourcentagedepense
                    size_hint:1,1
                    on_parent:self.show_pourcentage_depense()
        MDCard:
            size_hint_y: None
            height: dp(300)
            style: "elevated"
            elevation: 10
            radius: [20]

            MDBoxLayout:
                orientation: "vertical"
                padding: 0
                spacing: dp(10)

                # En-tête du card
                MDListItem:
                    theme_bg_color: "Custom"
                    md_bg_color: 139/255, 139/255, 139/255, 1
                    size_hint_y: None
                    height: dp(60)
                    radius:[20,20,0,0]

                    MDListItemLeadingIcon:
                        icon: "swap-horizontal-bold"

                    MDListItemHeadlineText:
                        text: "ajouter un dépense"
                        theme_text_color: "Custom"
                        text_color: 1, 1, 1, 1


                # Espaceur pour centrer le contenu
                Widget:
                    size_hint_y: 0.2

                # Premier champ
                MDTextField:
                    id: nom_depense
                    mode: "filled"
                    size_hint: 0.85, None
                    pos_hint: {"center_x": 0.5}

                    MDTextFieldHintText:
                        text: "nom de dépense"

                # Deuxième champ
                MDTextField:
                    id: somme_depense
                    mode: "filled"
                    size_hint: 0.85, None
                    pos_hint: {"center_x": 0.5}

                    MDTextFieldHintText:
                        text: "entrez la somme"


                # Bouton
                MDButton:
                    style: "filled"
                    size_hint: 0.85, None
                    height: dp(45)
                    pos_hint: {"center_x": 0.5}
                    on_press: root.add_expense()

                    MDButtonIcon:
                        icon: "check-underline-circle"

                    MDButtonText:
                        text: "ajouter le dépense"

                # Espaceur en bas
                Widget:
                    size_hint_y: 0.3


