

<PrincipalScreen@MDBoxLayout>
    orientation: "vertical"
    md_bg_color: app.opposite_bg_normal
    padding: dp(20)  # marge autour des enfants
    spacing: dp(10)  # espace entre enfants
<Gradient@MDNavigationDrawer>
    radius: [20, 20, 20, 20]
    size_hint_x: None
    width: "350dp"
    theme_text_color: "Custom"
    md_bg_color: app.drawer_color
    canvas.before:
        Color:
            rgba: app.drawer_color
        Rectangle:
            pos: self.pos
            size: self.size

    MDNavigationDrawerMenu:
        pos_hint: {"center_x": .5, "center_y": .5}
        canvas.before:
            Color:
                rgba: app.drawer_color
            Rectangle:
                pos: self.pos
                size: self.size

        MDBoxLayout:
            orientation: "vertical"
            adaptive_height: True
            spacing: dp(8)
            padding: [0, dp(10), 0, dp(20)]
            canvas.before:
                Color:
                    rgba: app.drawer_color
                Rectangle:
                    pos: self.pos
                    size: self.size

            FitImage:
                source: "assets/logo.png"
                size_hint: None, None
                size: dp(50), dp(50)
                pos_hint: {"center_x": .5}
                radius: [dp(25)]

            MDLabel:
                text: "Mail Pro"
                font_style: "Display"
                role: "small"
                halign: "center"
                theme_text_color: "Custom"
                text_color: 1, 1, 1, 1
                bold: True
                adaptive_height: True

        MDNavigationDrawerDivider:
            color: [1, 1, 1, 0.3]

        MDNavigationDrawerLabel:
            text: "MENU PRINCIPAL"
            theme_text_color: "Custom"
            text_color: 1, 1, 1, 0.8

        MDNavigationDrawerItem:
            theme_bg_color: "Custom"
            md_bg_color: app.drawer_color
            canvas.before:
                Color:
                    rgba: app.drawer_color
                Rectangle:
                    pos: self.pos
                    size: self.size
            on_release: app.manager.push("SalesPage")
            MDNavigationDrawerItemLeadingIcon:
                icon: "chart-areaspline"
                theme_text_color: "Custom"
                text_color: 1, 1, 1, 1
            MDNavigationDrawerItemText:
                role: "small"
                text: "statistique du jour"
                theme_text_color: "Custom"
                text_color: 1, 1, 1, 1

        MDNavigationDrawerItem:
            theme_bg_color: "Custom"
            md_bg_color: app.drawer_color
            canvas.before:
                Color:
                    rgba: app.drawer_color
                Rectangle:
                    pos: self.pos
                    size: self.size
            on_release: app.manager.push("WalletPage")
            MDNavigationDrawerItemLeadingIcon:
                icon: "wallet"
                theme_text_color: "Custom"
                text_color: 1, 1, 1, 1
            MDNavigationDrawerItemText:
                text: "Portefeuille"
                role: "small"
                theme_text_color: "Custom"
                text_color: 1, 1, 1, 1

        MDNavigationDrawerItem:
            theme_bg_color: "Custom"
            md_bg_color: app.drawer_color
            canvas.before:
                Color:
                    rgba: app.drawer_color
                Rectangle:
                    pos: self.pos
                    size: self.size
            on_release: app.manager.push("ProductPage")
            MDNavigationDrawerItemLeadingIcon:
                icon: "package-variant-closed"
                theme_text_color: "Custom"
                text_color: 1, 1, 1, 1
            MDNavigationDrawerItemText:
                text: "vos produits"
                role: "small"
                theme_text_color: "Custom"
                text_color: 1, 1, 1, 1

        MDNavigationDrawerItem:
            theme_bg_color: "Custom"
            md_bg_color: app.drawer_color
            canvas.before:
                Color:
                    rgba: app.drawer_color
                Rectangle:
                    pos: self.pos
                    size: self.size
            on_release: app.manager.push("ExpensesPage")
            MDNavigationDrawerItemLeadingIcon:
                icon: "cash-minus"
                theme_text_color: "Custom"
                text_color: 1, 1, 1, 1
            MDNavigationDrawerItemText:
                text: "Les dépenses"
                role: "small"
                theme_text_color: "Custom"
                text_color: 1, 1, 1, 1

        MDNavigationDrawerItem:
            theme_bg_color: "Custom"
            md_bg_color: app.drawer_color
            canvas.before:
                Color:
                    rgba: app.drawer_color
                Rectangle:
                    pos: self.pos
                    size: self.size
            on_release: app.manager.push("StatsPage")
            MDNavigationDrawerItemLeadingIcon:
                icon: "chart-bar"
                theme_text_color: "Custom"
                text_color: 1, 1, 1, 1
            MDNavigationDrawerItemText:
                text: "Statistiques"
                role: "small"
                theme_text_color: "Custom"
                text_color: 1, 1, 1, 1

        MDNavigationDrawerItem:
            theme_bg_color: "Custom"
            md_bg_color: app.drawer_color
            canvas.before:
                Color:
                    rgba: app.drawer_color
                Rectangle:
                    pos: self.pos
                    size: self.size
            on_release: app.manager.push("ProductPage")
            MDNavigationDrawerItemLeadingIcon:
                icon: "database"
                theme_text_color: "Custom"
                text_color: 1, 1, 1, 1
            MDNavigationDrawerItemText:
                text: "Vos données"
                role: "small"
                theme_text_color: "Custom"
                text_color: 1, 1, 1, 1

        MDNavigationDrawerDivider:
            color: 1, 1, 1, 0.3

        MDNavigationDrawerLabel:
            text: "AUTRES"
            theme_text_color: "Custom"
            text_color: 1, 1, 1, 0.8

        MDNavigationDrawerItem:
            theme_bg_color: "Custom"
            md_bg_color: app.drawer_color
            canvas.before:
                Color:
                    rgba: app.drawer_color
                Rectangle:
                    pos: self.pos
                    size: self.size
            on_release: app.manager.push("ProductPage")
            MDNavigationDrawerItemLeadingIcon:
                icon: "lightbulb-outline"
                theme_text_color: "Custom"
                text_color: 1, 1, 1, 1
            MDNavigationDrawerItemText:
                text: "Exemples"
                role: "small"
                theme_text_color: "Custom"
                text_color: 1, 1, 1, 1

        MDNavigationDrawerItem:
            theme_bg_color: "Custom"
            md_bg_color: app.drawer_color
            canvas.before:
                Color:
                    rgba: app.drawer_color
                Rectangle:
                    pos: self.pos
                    size: self.size
            on_release: app.manager.push("ProductPage")
            MDNavigationDrawerItemLeadingIcon:
                icon: "account-circle"
                theme_text_color: "Custom"
                text_color: 1, 1, 1, 1
            MDNavigationDrawerItemText:
                text: "Votre compte"
                role: "small"
                theme_text_color: "Custom"
                text_color: 1, 1, 1, 1

        MDNavigationDrawerItem:
            theme_bg_color: "Custom"
            md_bg_color: app.drawer_color
            canvas.before:
                Color:
                    rgba: app.drawer_color
                Rectangle:
                    pos: self.pos
                    size: self.size
            on_release: app.manager.push("ProductPage")
            MDNavigationDrawerItemLeadingIcon:
                icon: "logout"
                theme_text_color: "Custom"
                text_color: 1, 0.4, 0.4, 1
            MDNavigationDrawerItemText:
                text: "Déconnexion"
                role: "small"
                theme_text_color: "Custom"
                text_color: 1, 0.4, 0.4, 1
<AppBar@MDTopAppBar>
    type: "small"
    theme_bg_color: "Custom"
    md_bg_color: 1, 1, 1, 1

    MDTopAppBarLeadingButtonContainer:
        theme_bg_color: "Custom"
        md_bg_color: 1, 1, 1, 1

        MDActionTopAppBarButton:
            on_release: app.manager.toggle()
            icon: "menu"
            theme_icon_color: "Custom"
            icon_color: 0, 0, 0, 1   # icône noire

    MDTopAppBarTitle:
        text: "CompanyManager"
        theme_text_color: "Custom"
        text_color: 0, 0, 0, 1     # texte noir

    MDTopAppBarTrailingButtonContainer:
        theme_bg_color: "Custom"
        md_bg_color: 1, 1, 1, 1

        MDActionTopAppBarButton:
            icon: "attachment"
            theme_icon_color: "Custom"
            icon_color: 0, 0, 0, 1

        MDActionTopAppBarButton:
            icon: "calendar"
            theme_icon_color: "Custom"
            icon_color: 0, 0, 0, 1


        MDActionTopAppBarButton:
            icon: "dots-vertical"
            theme_icon_color: "Custom"
            icon_color: 0, 0, 0, 1
        MDSwitch:
            id: switch_control
            thumb_color_active: 1, 0.5, 0, 1
            on_active: app.on_switch_active(self, self.active)
            pos_hint: {"center_x": 0.8, "center_y": 0.5}


<Bg_mobile@MDNavigationDrawer>

    radius: [20, 20, 20, 20]
    size_hint_x: 1
    canvas.before:
        Color:
            rgba: 1, 1, 1, 1
        Rectangle:
            source: "images/poster_mobile.png"
            pos: self.pos
            size: self.size
    md_bg_color: 0, 0, 0, 0  # Rendre le drawer transparent
    elevation: 0  # Supprimer l'élévation qui peut causer des bordures
