

<PrincipalScreen@MDBoxLayout>
    orientation: "vertical"
    md_bg_color: app.opposite_bg_normal
    padding: dp(20)  # marge autour des enfants
    spacing: dp(10)  # espace entre enfants
<Gradient@MDNavigationDrawer>
    radius: [20, 20, 20, 20]
    size_hint_x: None
    width: "350dp"
    theme_text_color: "Custom"
    md_bg_color: app.drawer_color
    canvas.before:
        Color:
            rgba: app.drawer_color
        Rectangle:
            pos: self.pos
            size: self.size

    MDNavigationDrawerMenu:
        id:drawer_menu
        pos_hint: {"center_x": .5, "center_y": .5}
        canvas.before:
            Color:
                rgba: app.drawer_color
            Rectangle:
                pos: self.pos
                size: self.size

        MDBoxLayout:
            orientation: "vertical"
            adaptive_height: True
            spacing: dp(8)
            padding: [0, dp(10), 0, dp(20)]
            canvas.before:
                Color:
                    rgba: app.drawer_color
                Rectangle:
                    pos: self.pos
                    size: self.size

            FitImage:
                source: "assets/logo.png"
                size_hint: None, None
                size: dp(50), dp(50)
                pos_hint: {"center_x": .5}
                radius: [dp(25)]

            MDLabel:
                text: "Mail Pro"
                font_style: "Display"
                role: "small"
                halign: "center"
                theme_text_color: "Custom"
                text_color: 1, 1, 1, 1
                bold: True
                adaptive_height: True

        MDNavigationDrawerDivider:
            color: [1, 1, 1, 0.3]

        MDNavigationDrawerLabel:
            text: "MENU PRINCIPAL"
            theme_text_color: "Custom"
            text_color: 1, 1, 1, 0.8

        MDNavigationDrawerItem:
            id:item1
            theme_bg_color: "Custom"
            md_bg_color: app.drawer_color
            selected_color: app.drawer_color
            disabled : True
            on_release:
                if app.manager.current != "SalesPage": app.manager.go("SalesPage",0)
                selected = True
                self.disabled= True

            MDNavigationDrawerItemLeadingIcon:
                id:icon1
                icon: "chart-areaspline"

            MDNavigationDrawerItemText:
                id:text1
                role: "small"
                text: "statistique du jour"


        MDNavigationDrawerItem:
            id:item2
            theme_bg_color: "Custom"
            md_bg_color: app.drawer_color
            canvas.before:
                Color:
                    rgba: app.drawer_color
                Rectangle:
                    pos: self.pos
                    size: self.size
            on_release:
                app.manager.go("WalletPage",1)
                selected = True

            MDNavigationDrawerItemLeadingIcon:
                id:icon2
                icon: "wallet"
                theme_text_color: "Custom"
                text_color: 1, 1, 1, 1
            MDNavigationDrawerItemText:
                id:text2
                text: "Portefeuille"
                role: "small"
                theme_text_color: "Custom"
                text_color: 1, 1, 1, 1

        MDNavigationDrawerItem:
            id:item3
            theme_bg_color: "Custom"
            md_bg_color: app.drawer_color
            canvas.before:
                Color:
                    rgba: app.drawer_color
                Rectangle:
                    pos: self.pos
                    size: self.size
            on_release: app.manager.go("ProductPage",2)
            MDNavigationDrawerItemLeadingIcon:
                id:icon3
                icon: "package-variant-closed"
                theme_text_color: "Custom"
                text_color: 1, 1, 1, 1
            MDNavigationDrawerItemText:
                id:text3
                text: "vos produits"
                role: "small"
                theme_text_color: "Custom"
                text_color: 1, 1, 1, 1

        MDNavigationDrawerItem:
            id:item4
            theme_bg_color: "Custom"
            md_bg_color: app.drawer_color
            canvas.before:
                Color:
                    rgba: app.drawer_color
                Rectangle:
                    pos: self.pos
                    size: self.size
            on_release: app.manager.go("ExpensesPage",3)
            MDNavigationDrawerItemLeadingIcon:
                id:icon4
                icon: "cash-minus"
                theme_text_color: "Custom"
                text_color: 1, 1, 1, 1
            MDNavigationDrawerItemText:
                id:text4
                text: "Les dépenses"
                role: "small"
                theme_text_color: "Custom"
                text_color: 1, 1, 1, 1

        MDNavigationDrawerItem:
            id:item5
            theme_bg_color: "Custom"
            md_bg_color: app.drawer_color
            canvas.before:
                Color:
                    rgba: app.drawer_color
                Rectangle:
                    pos: self.pos
                    size: self.size
            on_release: app.manager.go("StatsPage",4)
            MDNavigationDrawerItemLeadingIcon:
                id:icon5
                icon: "chart-bar"
                theme_text_color: "Custom"
                text_color: 1, 1, 1, 1
            MDNavigationDrawerItemText:
                id:text5
                text: "Statistiques"
                role: "small"
                theme_text_color: "Custom"
                text_color: 1, 1, 1, 1

        MDNavigationDrawerDivider:
            color: 1, 1, 1, 0.3

        MDNavigationDrawerLabel:
            text: "AUTRES"
            theme_text_color: "Custom"
            text_color: 1, 1, 1, 0.8

        MDNavigationDrawerItem:
            id:item6
            theme_bg_color: "Custom"
            md_bg_color: app.drawer_color
            canvas.before:
                Color:
                    rgba: app.drawer_color
                Rectangle:
                    pos: self.pos
                    size: self.size
            on_release:
                app.show_update_profile()
                self.selected=True
            MDNavigationDrawerItemLeadingIcon:
                id:icon6
                icon: "account-circle"
                theme_text_color: "Custom"
                text_color: 1, 1, 1, 1
            MDNavigationDrawerItemText:
                id:text6
                text: "Votre compte"
                role: "small"
                theme_text_color: "Custom"
                text_color: 1, 1, 1, 1

        MDNavigationDrawerItem:
            id:item7
            theme_bg_color: "Custom"
            md_bg_color: app.drawer_color
            selected_color: app.drawer_color
            on_release:
                if app.manager.current != "user_creation": app.manager.go("user_creation")

            canvas.before:
                Color:
                    rgba: app.drawer_color
                Rectangle:
                    pos: self.pos
                    size: self.size
            MDNavigationDrawerItemLeadingIcon:
                id:icon7
                icon: "logout"

            MDNavigationDrawerItemText:
                id:text7
                text: "Déconnexion"
                role: "small"

<AppBar@MDTopAppBar>
    type: "small"
    theme_bg_color: "Custom"
    md_bg_color: 1, 1, 1, 1

    MDTopAppBarLeadingButtonContainer:
        theme_bg_color: "Custom"
        md_bg_color: 1, 1, 1, 1

        MDActionTopAppBarButton:
            on_release: app.manager.toggle()
            icon: "menu"
            theme_icon_color: "Custom"
            icon_color: 0, 0, 0, 1   # icône noire

    MDTopAppBarTitle:
        text: "CompanyManager"
        theme_text_color: "Custom"
        text_color: 0, 0, 0, 1     # texte noir

    MDTopAppBarTrailingButtonContainer:
        theme_bg_color: "Custom"
        md_bg_color: 1, 1, 1, 1

        MDActionTopAppBarButton:
            icon: "attachment"
            theme_icon_color: "Custom"
            icon_color: 0, 0, 0, 1

        MDActionTopAppBarButton:
            icon: "calendar"
            theme_icon_color: "Custom"
            icon_color: 0, 0, 0, 1


        MDActionTopAppBarButton:
            icon: "dots-vertical"
            theme_icon_color: "Custom"
            icon_color: 0, 0, 0, 1
        MDSwitch:
            id: switch_control
            thumb_color_active: 1, 0.5, 0, 1
            on_active: app.on_switch_active(self, self.active)
            pos_hint: {"center_x": 0.8, "center_y": 0.5}


<Bg_mobile@MDNavigationDrawer>

    radius: [20, 20, 20, 20]
    size_hint_x: 1
    canvas.before:
        Color:
            rgba: 1, 1, 1, 1
        Rectangle:
            source: "images/poster_mobile.png"
            pos: self.pos
            size: self.size
    md_bg_color: 0, 0, 0, 0  # Rendre le drawer transparent
    elevation: 0  # Supprimer l'élévation qui peut causer des bordures
