#:import components components.components

<InsertProduct>:
    size_hint_x: 1
    radius: [15]
    style: "elevated"
    elevation: 10

    MDBoxLayout:
        adaptive_height: True
        padding: dp(20)
        spacing: dp(20)
        pos_hint:{"center_x":.5,"center_y":.5}
        orientation: "vertical"

        CTextField:
            size_hint_y: None
            height: dp(50)
            id: nom
            mode: "filled"
            MDTextFieldHelperText:
                text: " ex: Pantalon"
                text_color_focus: "grey"
            MDTextFieldHintText:
                text: "entrez le nom du produit"
                text_color_normal: "grey"



        MDCard:
            size_hint: 0.6, None
            height: dp(50)
            radius: [20]
            elevation: 8
            md_bg_color: [1,1,1,1]
            pos_hint: {"center_x": 0.5}
            on_release: self.parent.parent.open_menu(drop_text)
            MDBoxLayout:
                orientation: "vertical"
                padding: dp(5)
                spacing: dp(5)
                size_hint_y: None
                height: self.minimum_height
                pos_hint: {"center_x": 0.5}

                MDDropDownItem:
                    pos_hint: {"center_x": 0.5}
                    id: dropdown
                    on_release: self.parent.parent.parent.parent.open_menu(self)
                    MDDropDownItemText:
                        pos_hint: {"center_x": 0.5}
                        font_style: "Title"
                        role:"medium"
                        valign:"middle"
                        halign: "center"
                        id: drop_text
                        text: "selectionnez"


        CTextField:
            size_hint_y: None
            height: dp(50)
            id: pu
            MDTextFieldHelperText:
                text: "ex: 8000"
            MDTextFieldHintText:
                text: "entrez son prix unitaire"
        CTextField:
            size_hint_y: None
            height: dp(50)
            id: qt
            MDTextFieldHelperText:
                text: "ex: 8000"
            MDTextFieldHintText:
                text: "entrez le quantité"

        MDButton:
            size_hint_y: None
            height: dp(50)
            pos_hint:{"center_x":.5}
            style: "filled"
            on_press: root.add()
            MDButtonIcon:
                icon: "check-underline-circle"
            MDButtonText:
                text: "créer le produit"

<SaleProduct>:
    size_hint_x: 1
    radius: [15]
    style: "elevated"
    elevation: 10
    MDBoxLayout:
        adaptive_height: True
        orientation: "vertical"
        padding: dp(20)
        spacing: dp(20)
        pos_hint:{"center_x":.5,"center_y":.5}
        CTextField:
            id: nom_produit_vente
            MDTextFieldHelperText:
                text: " ex: mon produit"
                text_color_focus: "grey"
            MDTextFieldHintText:
                text: "entrez le nom du produit"
                text_color_normal: "grey"
        CTextField:
            id: qt_produit_vente
            MDTextFieldHelperText:
                text: " ex: 3"
                text_color_focus: "grey"
            MDTextFieldHintText:
                text: "entrez le qt du produit à vendre"
                text_color_normal: "grey"
        MDButton:
            on_press: root.sale_product()
            pos_hint: {"center_x": 0.5, "center_y": 0.5}
            style: "filled"
            MDButtonIcon:
                icon: "check-underline-circle"
            MDButtonText:
                text: "vendre le produit"

<InsertProductType>:
    size_hint_x: 1
    radius: [15]
    style: "elevated"
    elevation: 10
    MDBoxLayout:
        adaptive_height: True
        orientation: "vertical"
        padding: dp(20)
        spacing: dp(20)
        pos_hint:{"center_x":.5,"center_y":.5}
        CTextField:
            id: typetoinsert
            mode: "filled"
            size_hint_y: 0.1
            MDTextFieldHelperText:
                text: " ex: haut léger"
                text_color_focus: "grey"
            MDTextFieldHintText:
                text: "entrez le type ici"
                text_color_normal: "grey"
        MDButton:
            on_press: root.add_type()
            pos_hint: {"center_x": 0.5, "center_y": 0.5}
            style: "filled"
            MDButtonIcon:
                icon: "check-underline-circle"
            MDButtonText:
                text: "insérer le type"

<ProductNavigation>:
    InsertProduct:
    SaleProduct:
    InsertProductType:

<ProductsPage>:
    padding: dp(5)
    spacing: dp(5)
    orientation: "vertical"


    MDSegmentedButton:
        size_hint: 1, None
        height: dp(40)
        radius: [20, 0, 0, 20]
        MDSegmentedButtonItem:
            active: True
            on_active: root.change_page_screen()
            MDSegmentButtonLabel:
                text: "option normale"
        MDSegmentedButtonItem:
            on_active:
                root.change_page_screen_pop()
                root.ids.productlist.ids.listproducts.show_list()
            MDSegmentButtonLabel:
                text: "option avancée"

    MDScreenManager:
        id: product_sreen_manager
        size_hint_y: None
        height: dp(550)
        MDScreen:
            name: "screenOne"
            DefaultScreen:
                id: defaultscreen

        MDScreen:
            name: "screenTwo"
            ProductList:
                id: productlist



<DefaultScreen@MDScrollView>:
    MDBoxLayout:
        id: product_page_1
        orientation: "horizontal"
        size_hint_y:None
        height:self.minimum_height
        MDBoxLayout:
            id: product_page_1_section_2
            orientation: "vertical"
            spacing: dp(20)
            padding: dp(20)
            size_hint_x: 0.4
            adaptive_height:True
            MDTabsPrimary:
                size_hint_y: None
                height:dp(70)
                id: tabs
                pos_hint: {"center_x": .5, "center_y": 0.95}
                radius: [7]
                #theme_bg_color: "Custom"
                #md_bg_color: 98/255,156/255,196/255,1

                MDTabsItem:
                    on_release: root.parent.parent.parent.change_screen_pop()
                    MDTabsItemText
                        text: "Insérer un produit"
                    MDTabsItemIcon
                        icon: "package-down"

                MDTabsItem:
                    on_release: root.parent.parent.parent.change_screen()
                    MDTabsItemText
                        text: "Vendre un produit"
                    MDTabsItemIcon
                        icon: "package-up"
                MDTabsItem:
                    on_release: root.parent.parent.parent.change_screen_type()
                    MDTabsItemText
                        text: "insérer un type"
                    MDTabsItemIcon
                        icon: "package"

            MDScreenManager:
                id: screen_manager
                size_hint_y: None
                height: dp(450)

                MDScreen:
                    name: "screen1"
                    InsertProduct:
                        id:insertproduct

                MDScreen:
                    name: "screen2"
                    SaleProduct:
                        id:delectproduct

                MDScreen:
                    name: "screen3"
                    InsertProductType:
                        id:insertproducttype



        Sliver:
            id: sliver_box
            size_hint_y: None
            height: dp(550)
            size_hint_x:.6
            #md_bg_color: 1, 0, 0, 0.3
<Sliver@MDScrollView>:
    MDSliverAppbar:
        background_color: 1,1,1,1 # couleur 2d4a50
        hide_appbar: True
        size_hint:1, None
        height: dp(550)

        MDTopAppBar:
            type: "medium"
            size_hint_y:None
            height:dp(50)

            MDTopAppBarLeadingButtonContainer:
                MDActionTopAppBarButton:
                    icon: "package"

            MDTopAppBarTitle:
                text: "vos produit"

            MDTopAppBarTrailingButtonContainer:
                MDActionTopAppBarButton:
                    icon: "attachment"
                MDActionTopAppBarButton:
                    icon: "calendar"
                MDActionTopAppBarButton:
                    icon: "dots-vertical"

        MDSliverAppbarHeader:
            FitImage:
                source: "images/stock.png"

        Content:
            id: content
            size_hint_y: None
            height: dp(450)

<Content>:
    theme_bg_color: "Custom"
    md_bg_color: 218/255,236/255,246/255,1
    MDBoxLayout:
        adaptive_height:True
        orientation:"vertical"
        MDBoxLayout:
            adaptive_height:True
            id: searchcontainer
            spacing: dp(7)
            padding: dp(7)
            MDTextField:
                size_hint_y: None
                height: dp(36)
                id: search_textfield
                on_text: root.search_order()
                size_hint_x: 0.6
                radius: [15]
                mode: "filled"
            MDButton:
                size_hint_y: None
                height: dp(36)
                on_release: root.search_order()
                size_hint_x: 0.3
                radius: [5]
                style: "filled"
                MDButtonIcon:
                    icon: "magnify"
                MDButtonText:
                    text: "chercher"

        ListProducts:
            id: listproducts
            size_hint: 1, None
            height: dp(400)

<ListProducts>:
    MDRecycleView:
        id: rv
        viewclass:"ProductRow"
        key_size:"height"
        RecycleBoxLayout:
            default_size: None, dp(100)
            default_size_hint: 1, None
            size_hint_y:None
            height: self.minimum_height
            orientation:"vertical"


<ProductRow>:
    orientation:"horizontal"
    spacing:dp(20)
    adaptive_height:True

    MDBoxLayout:
        adaptive_height:True
        orientation:"vertical"
        size_hint_x:.1
        MDButton:
            on_release: self.parent.parent.parent.parent.parent.sell_product(root.nom_produit)
            md_bg_color:[0,0,0.2,0]
            MDButtonIcon:
                icon: "plus"
                icon_size: "60dp"
            MDButtonText:
                pos_hint: {"center_x": .5, "center_y": .5}
                text:"Vendre"
        MDIconButton:
            icon: "trash-can-outline"
            icon_size: "60dp"
            on_release: on_release:self.parent.parent.parent.parent.parent.remove_product(root.nom_produit)
    MDBoxLayout:
        adaptive_height:True
        orientation:"vertical"
        size_hint_x:.6
        padding:dp(10)
        MDLabel:
            halign: "center"
            valign: "middle"
            text:root.nom_produit
            bold:True
            size_hint_y:None
            height: dp(36)
        MDLabel:
            halign: "center"
            valign: "middle"
            text: "Type :"+root.type
            size_hint_y:None
            height: dp(36)
    MDBoxLayout:
        size_hint_x:.3
        adaptive_height:True
        orientation:"vertical"
        padding:dp(10)
        MDLabel:
            halign: "center"
            valign: "middle"
            text: "prix :"+root.prix_unitaire
            size_hint_y:None
            height: dp(36)

        MDLabel:
            halign: "center"
            valign: "middle"
            size_hint_y:None
            height: dp(36)
            text: "Quantité :"+root.qt



<ProductList>:
    MDBoxLayout:
        id: product_page_2
        orientation: "vertical"
        padding: dp(20)
        adaptive_height:True
        CCard:
            id:stock_card
            size_hint_x: .7
            size_hint_y: None
            height: dp(550)
            CBox:
                orientation: "vertical"
                adaptive_height:True
                MDBoxLayout:
                    padding:dp(15)
                    spacing:dp(15)
                    size_hint_y: None
                    height: dp(70)
                    size_hint_x:1
                    MDLabel:
                        size_hint_y:None
                        height:dp(55)

                        halign: "center"
                        valign: "middle"
                        text:"stock initiale"
                        theme_bg_color:"Custom"
                        md_bg_color:30/255,129/255,176/255,1
                        text_color:[1,1,1,1]
                    MDLabel:
                        size_hint_y:None
                        height:dp(55)
                        halign: "center"
                        valign: "middle"
                        text:"produit vendu"
                        theme_bg_color:"Custom"
                        md_bg_color:30/255,129/255,176/255,1
                        text_color:[1,1,1,1]
                    MDLabel:
                        size_hint_y:None
                        height:dp(55)
                        halign: "center"
                        valign: "middle"
                        text:"produit perimé"
                        theme_bg_color:"Custom"
                        md_bg_color:30/255,129/255,176/255,1
                        text_color:[1,1,1,1]
                    MDLabel:
                        size_hint_y:None
                        height:dp(55)
                        halign: "center"
                        valign: "middle"
                        text:"reste en stock"
                        theme_bg_color:"Custom"
                        md_bg_color:30/255,129/255,176/255,1
                        text_color:[1,1,1,1]
                    MDIconButton:
                        size_hint_y:None
                        height:dp(55)
                        height: dp(40)
                        icon: "file-download"  # ou "file-table-box", ou "export"
                        on_release: app.export_to_excel()
                        tooltip_text: "Exporter vers Excel"


                ProductResume:
                    id: listproducts
                    size_hint: 1, None
                    height: dp(400)
        MDBoxLayout:
            id: product_page_2_section_2
            size_hint_y:None
            height:dp(500)
            size_hint_x: 0.3
            orientation: "vertical"
            MDBoxLayout:
                size_hint_x:1
                spacing:dp(7)
                pos_hint: {"center_y": 1.1}
                adaptive_height:True
                MDButton:
                    size_hint_y: None
                    height: dp(36)
                    id:date_button
                    theme_bg_color:"Custom"
                    md_bg_color:171/255,219/255,227/255,1
                    radius:[15]
                    on_release:
                        root.show_date_picker()
                    MDButtonText:
                        text:"Date"

                MDButton:
                    size_hint_y: None
                    height: dp(36)
                    theme_bg_color:"Custom"
                    md_bg_color:171/255,219/255,227/255,1
                    radius:[15]
                    on_release:
                        root.show_modal_date_picker()
                    MDButtonText:
                        text:"Période"

                MDButton:
                    theme_bg_color:"Custom"
                    md_bg_color:171/255,219/255,227/255,1
                    radius:[15]
                    size_hint_y: None
                    on_release:
                        root.show_month_picker()
                    MDButtonText:
                        text:"Mois"
                MDButton:
                    theme_bg_color:"Custom"
                    md_bg_color:171/255,219/255,227/255,1
                    radius:[15]
                    size_hint_y: None
                    on_release:
                        root.show_year_picker()
                    MDButtonText:
                        text:"Année"
            CCard:
                size_hint_x:1
                SalesStatContent:
                    id:salescontainer
                    size_hint_y: None
                    height: dp(300)



<SalesStatContent>:
    orientation:'vertical'

    MDListItem:
        theme_bg_color: "Custom"
        md_bg_color: 186/255,169/255,155/255,1
        size_hint_y: None
        height: dp(40)
        radius:[20,20,0,0]
        spacing:dp(10)
        padding:dp(10)
        pos_hint: {"center_y": .8}

        MDListItemLeadingIcon:
            icon: "sale"
        MDListItemHeadlineText:
            text: "pourcentage de vente des produits"

    MDBoxLayout:
        id: searchproductsold
        spacing: dp(7)
        padding: dp(7)
        adaptive_height:True
        pos_hint: {"center_y": 0.7}
        MDTextField:
            size_hint_y: None
            height: dp(36)

            id: textfieldproductsold
            on_text: root.search_order()
            size_hint_x: 0.4
            radius: [5]
            mode: "filled"
        MDButton:
            size_hint_y: None
            height: dp(36)
            on_release: root.search_order()
            size_hint_x: 0.3
            radius: [5]
            style: "filled"
            MDButtonIcon:
                icon: "magnify"
            MDButtonText:
                text: "chercher"
    PourcentagePVG:
        id:pourcentagepvg
        size_hint_x:1
        size_hint_y: None
        height: dp(350)
<PourcentagePVG>:
    MDRecycleView:
        id: pv
        viewclass:"ProductRowPV"
        key_size:"height"
        RecycleBoxLayout:
            default_size: None, dp(40)
            default_size_hint: 1, None
            size_hint_y:None
            height: self.minimum_height
            orientation:"vertical"
<ProductRowPV>:
    orientation:"horizontal"
    spacing:dp(20)
    padding:dp(20)
    adaptive_height:True
    MDLabel:
        halign: "center"
        valign: "middle"
        size_hint_y: None
        height: dp(36)
        text:root.product_name
        font_style:"RobotoBold"
    MDDivider:
        orientation: "vertical"
    MDLabel:
        halign: "center"
        valign: "middle"
        size_hint_y: None
        height: dp(36)
        text:root.sale_percent



<ProductResume>:
    MDRecycleView:
        id: pr
        viewclass:"Resume"
        key_size:"height"
        RecycleBoxLayout:
            default_size: None, dp(40)
            default_size_hint: 1, None
            size_hint_y:None
            height: self.minimum_height
            orientation:"vertical"

<Resume>:
    adaptive_height:True
    orientation:"horizontal"
    spacing:dp(20)
    padding:dp(20)

    MDLabel:
        size_hint_y: None
        height: dp(36)
        halign: "center"
        valign: "middle"
        text:root.initiale
    MDDivider:
        orientation:"vertical"
        size_hint_x:.05
    MDLabel:
        size_hint_y: None
        height: dp(36)
        halign: "center"
        valign: "middle"
        text:root.vendu
    MDDivider:
        orientation:"vertical"
        size_hint_x:.05
    MDLabel:
        size_hint_y: None
        height: dp(36)
        halign: "center"
        valign: "middle"
        text:root.perime
    MDDivider:
        orientation:"vertical"
        color:0.9569, 0.5373, 0.2078, 1
        size_hint_x:.05
    MDLabel:
        size_hint_y: None
        height: dp(36)
        halign: "center"
        valign: "middle"
        text:root.reste
    MDWidget:
        size_hint_x:.09







