#:import components components.components

<InsertProduct>:
    #name:"insert_product"
    size_hint_x: 1
    radius: [15]
    style: "elevated"
    elevation: 10
    MDBoxLayout:
        padding:dp(10)
        spacing:dp(5)
        orientation:"vertical"
        CLabel:
            text_color:0,0,0,1
            size_hint_y:0.1
            text: "Insertion de votre produit"
            role: "small"
        MDTextField:
            size_hint_x: 0.8
            size_hint_y: None
            height: "20dp"
            id:nom
            mode: "filled"
            MDTextFieldHelperText:
                text: " ex: Pantalon"
                text_color_focus: "grey"
            MDTextFieldHintText:
                text: "entrez le nom du produit"
                text_color_normal: "grey"
        MDExpansionPanel:
            id: panel
            pos_hint: {"center_x": .5, "center_y": .5}
            size_hint: 0.9, None
            height: "200dp"

            MDExpansionPanelHeader:

                MDListItem:
                    theme_bg_color: "Custom"
                    md_bg_color: self.theme_cls.surfaceContainerLowColor
                    ripple_effect: False

                    MDListItemSupportingText:
                        text: "Supporting text"
                    TrailingPressedIconButton:
                        id: chevron
                        icon: "chevron-right"
                        on_release: self.parent.parent.parent.parent.parent.parent.tap_expansion_chevron(panel, chevron)

            MDExpansionPanelContent:
                orientation: "vertical"
                padding: "12dp", 0, "12dp", 0





        MDTextField:

            id:pu
            mode:"filled"
            size_hint_y:0.25
            MDTextFieldHelperText:
                text:"ex: 8000"
            MDTextFieldHintText:
                text:"entrez son prix unitaire"
        MDTextField:

            id:qt
            mode:"filled"
            size_hint_y:0.25
            MDTextFieldHelperText:
                text:"ex: 8000"
            MDTextFieldHintText:
                text:"entrez le quantité"

        MDButton:
            pos_hint: {"center_x": 0.5, "center_y": 0.5}
            style: "filled"
            on_press:root.add()
            MDButtonIcon:
                icon: "check-underline-circle"
            MDButtonText:
                text: "créer le produit"
<SaleProduct>:
    #name:"delete_product"

    size_hint_x: 1
    radius: [15]
    style: "elevated"
    elevation: 10
    MDBoxLayout:
        orientation:"vertical"
        spacing:dp(20)
        padding:dp(20)
        MDLabel:
            text_color:0,0,0,1
            size_hint_y:0.1
            text: "vente de votre produit"
            halign: "left"
            text_color: 1,1,1,1
            font_style: "OutfitBlack"
            role: "small"
            bold: True
        MDTextField:

            id:nom_produit_vente
            mode: "filled"
            size_hint_y:0.1
            MDTextFieldHelperText:
                text: " ex: P0001"
                text_color_focus: "grey"
            MDTextFieldHintText:
                text: "entrez le nom du produit"
                text_color_normal: "grey"
        MDTextField:

            id:qt_produit_vente
            mode: "filled"
            size_hint_y:0.1
            MDTextFieldHelperText:
                text: " ex: 3"
                text_color_focus: "grey"
            MDTextFieldHintText:
                text: "entrez le qt du produit à vendre"
                text_color_normal: "grey"

        MDButton:
            on_press:root.sale_product()
            pos_hint: {"center_x": 0.5, "center_y": 0.5}
            style: "filled"
            MDButtonIcon:
                icon: "check-underline-circle"
            MDButtonText:
                text: "vendre le produit"
<InsertProductType>:
    #name:"insert_type_product"
    size_hint_x: 1
    radius: [15]
    style: "elevated"
    elevation: 10
    MDBoxLayout:
        orientation:"vertical"
        spacing:dp(20)
        padding:dp(20)
        MDLabel:
            text_color:0,0,0,1
            size_hint_y:0.1
            text: "Insérez ici un nouveau type de produit"
            halign: "left"
            text_color: 1,1,1,1
            font_style: "OutfitBlack"
            role: "small"
            bold: True
        MDTextField:
            id:typetoinsert
            mode: "filled"
            size_hint_y:0.1
            MDTextFieldHelperText:
                text: " ex: haut léger"
                text_color_focus: "grey"
            MDTextFieldHintText:
                text: "entrez le type ici"
                text_color_normal: "grey"

        MDButton:
            on_press:root.add_type()
            pos_hint: {"center_x": 0.5, "center_y": 0.5}
            style: "filled"
            MDButtonIcon:
                icon: "check-underline-circle"
            MDButtonText:
                text: "insérer le type"

<ProductNavigation>:
    InsertProduct:
    SaleProduct:
    InsertProductType:

<DefaultScreen@MDScreen>:
    MDBoxLayout:
        MDBoxLayout:
            orientation:"vertical"
            spacing:dp(20)
            padding:dp(20)
            size_hint_x:0.3
            size_hint_y:1
            MDTabsPrimary:
                id: tabs
                pos_hint: {"center_x": .5, "center_y": 0.95}
                radius: [7]
                #theme_bg_color: "Custom"
                #md_bg_color: 98/255,156/255,196/255,1

                MDTabsItem:
                    on_release: root.parent.change_screen_pop()
                    MDTabsItemText
                        text: "Insérer un produit"
                    MDTabsItemIcon
                        icon: "package-down"

                MDTabsItem:
                    on_release: root.parent.parent.parent.change_screen()
                    MDTabsItemText
                        text: "Vendre un produit"
                    MDTabsItemIcon
                        icon: "package-up"
                MDTabsItem:
                    on_release: root.parent.parent.parent.change_screen_type()
                    MDTabsItemText
                        text: "insérer un type"
                    MDTabsItemIcon
                        icon: "package"

            MDScreenManager:
                id: screen_manager

                MDScreen:
                    name: "screen1"
                    InsertProduct:
                        id:insertproduct
                MDScreen:
                    name: "screen2"
                    SaleProduct:
                        id:delectproduct
                MDScreen:
                    name: "screen3"
                    InsertProductType:
                        id:insertproducttype



        Sliver:
            id: sliver_box
            size_hint_y: 1
            size_hint_x: 0.65

<ProductsPage>:
    padding: dp(5)
    spacing:dp(5)
    orientation:"vertical"
    MDSegmentedButton:
        size_hint: 1,.05
        radius:[20]

        MDSegmentedButtonItem:
            active: True
            on_active: root.change_page_screen()

            MDSegmentButtonLabel:
                text: "option nomrale"

        MDSegmentedButtonItem:
            on_active: root.change_page_screen_pop();root.ids.productlist.ids.listproducts.show_list()

            MDSegmentButtonLabel:
                text: "option avancée"
    MDScreenManager:
        id: product_sreen_manager

        MDScreen:
            name: "screenOne"
            DefaultScreen:
                id:defaultscreen



        MDScreen:
            name: "screenTwo"
            ProductList:
                id:productlist

<ProductList>:
    MDBoxLayout:
        CCard:
            size_hint_x:.7
            CBox:
                orientation:"vertical"
                MDBoxLayout:
                    size_hint_x:1
                    MDLabel:
                        text:"stock initiale"
                        theme_bg_color:"Custom"
                        md_bg_color:30/255,129/255,176/255,1
                        text_color:[1,1,1,1]
                    MDLabel:
                        text:"produit vendu"
                        theme_bg_color:"Custom"
                        md_bg_color:30/255,129/255,176/255,1
                        text_color:[1,1,1,1]
                    MDLabel:
                        text:"produit perimé"
                        theme_bg_color:"Custom"
                        md_bg_color:30/255,129/255,176/255,1
                        text_color:[1,1,1,1]
                    MDLabel:
                        text:"reste en stock"
                        theme_bg_color:"Custom"
                        md_bg_color:30/255,129/255,176/255,1
                        text_color:[1,1,1,1]
                    MDIconButton:
                        icon: "file-download"  # ou "file-table-box", ou "export"
                        on_release: app.export_to_excel()
                        tooltip_text: "Exporter vers Excel"


                ProductResume:
                    id: listproducts
                    size_hint: 1, None
                    height: 400
        MDBoxLayout:
            size_hint_x:0.3
            orientation:"vertical"
            MDBoxLayout:
                size_hint:1,0.15
                spacing:dp(7)
                padding:dp(7)

                MDButton:
                    id:date_button
                    theme_bg_color:"Custom"
                    md_bg_color:171/255,219/255,227/255,1
                    radius:[15]
                    on_release:
                        root.show_date_picker()
                    MDButtonText:
                        text:"Date"

                MDButton:
                    theme_bg_color:"Custom"
                    md_bg_color:171/255,219/255,227/255,1
                    radius:[15]
                    on_release:
                        root.show_modal_date_picker()
                    MDButtonText:
                        text:"Période"

                MDButton:
                    theme_bg_color:"Custom"
                    md_bg_color:171/255,219/255,227/255,1
                    radius:[15]
                    on_release:
                        root.show_year()
                    MDButtonText:
                        text:"Mois"
                MDButton:
                    theme_bg_color:"Custom"
                    md_bg_color:171/255,219/255,227/255,1
                    radius:[15]
                    MDButtonText:
                        text:"Année"
            CCard:
                size_hint_x:1
                SalesStatContent:
                    id:salescontainer



<SalesStatContent>:
    orientation:'vertical'
    MDListItem:
        theme_bg_color: "Custom"
        md_bg_color: 186/255,169/255,155/255,1
        size_hint_y: 0.1
        radius:[20,20,0,0]
        spacing:dp(10)
        padding:dp(10)
        pos_hint: {"y": 0.7}
        halign:"center"

        MDListItemLeadingIcon:
            icon: "sale"
        MDListItemHeadlineText:
            text: "pourcentage de vente des produits"

    MDBoxLayout:
        id: searchproductsold
        spacing: dp(7)
        padding: dp(7)
        size_hint_y:0.1
        MDTextField:
            size_hint_y:.1
            id: textfieldproductsold
            on_text: root.search_order()
            size_hint_x: 0.4
            radius: [5]
            mode: "filled"
        MDButton:
            on_release: root.search_order()
            size_hint_x: 0.3
            size_hint_y:.1
            radius: [5]
            style: "filled"
            MDButtonIcon:
                icon: "magnify"
            MDButtonText:
                text: "chercher"
    PourcentagePVG:
        id:pourcentagepvg
        size_hint:1,0.7
<PourcentagePVG>:
    MDRecycleView:
        id: pv
        viewclass:"ProductRowPV"
        key_size:"height"
        RecycleBoxLayout:
            default_size: None, dp(40)
            default_size_hint: 1, None
            size_hint_y:None
            height: self.minimum_height
            orientation:"vertical"
<ProductRowPV>:
    orientation:"horizontal"
    spacing:dp(20)
    padding:dp(20)
    MDLabel:
        text:root.product_name
    MDLabel:
        text:root.sale_percent



<ProductResume>:
    MDRecycleView:
        id: pr
        viewclass:"Resume"
        key_size:"height"
        RecycleBoxLayout:
            default_size: None, dp(40)
            default_size_hint: 1, None
            size_hint_y:None
            height: self.minimum_height
            orientation:"vertical"

<Resume>:
    orientation:"horizontal"
    spacing:dp(20)
    padding:dp(20)
    MDLabel:
        text:root.initiale
    MDLabel:
        text:root.vendu
    MDLabel:
        text:root.perime
    MDLabel:
        text:root.reste






<Sliver@MDScreen>:
    MDSliverAppbar:
        background_color: 1,1,1,1 # couleur 2d4a50
        hide_appbar: True

        MDTopAppBar:
            type: "medium"

            MDTopAppBarLeadingButtonContainer:
                MDActionTopAppBarButton:
                    icon: "package"

            MDTopAppBarTitle:
                text: "vos produit"

            MDTopAppBarTrailingButtonContainer:
                MDActionTopAppBarButton:
                    icon: "attachment"
                MDActionTopAppBarButton:
                    icon: "calendar"
                MDActionTopAppBarButton:
                    icon: "dots-vertical"

        MDSliverAppbarHeader:
            FitImage:
                source: "images/playabg.jpg"

        Content:
            id: content

<Content>:
    orientation: "vertical"
    padding: "12dp"
    theme_bg_color: "Custom"
    md_bg_color: 218/255,236/255,246/255,1

    MDBoxLayout:
        id: searchcontainer
        spacing: dp(7)
        padding: dp(7)
        MDTextField:
            id: search_textfield
            on_text: root.search_order()
            size_hint_x: 0.6
            radius: [15]
            mode: "filled"
        MDButton:
            on_release: root.search_order()
            size_hint_x: 0.3
            radius: [5]
            style: "filled"
            MDButtonIcon:
                icon: "magnify"
            MDButtonText:
                text: "chercher"

    ListProducts:
        id: listproducts
        size_hint: 1, None
        height: 800
<Produit>:
    orientation:"horizontal"
    spacing:dp(20)
    MDLabel:
        text:root.type_produit

<ListProducts>:
    MDRecycleView:
        id: rv
        viewclass:"ProductRow"
        key_size:"height"
        RecycleBoxLayout:
            default_size: None, dp(40)
            default_size_hint: 1, None
            size_hint_y:None
            height: self.minimum_height
            orientation:"vertical"
<ProductRow>:
    orientation:"horizontal"
    spacing:dp(20)
    MDIconButton:
        icon:"package-down"
        size_hint:None,None
        size:dp(40),dp(40)
        on_release: self.parent.parent.parent.parent.sell_product(root.nom_produit)
    MDLabel:
        text:root.nom_produit
    MDLabel:
        text:root.prix_unitaire
    MDLabel:
        text:root.qt
    MDLabel:
        text:root.type
    MDButton:
        text:'-'
        theme_bg_color:'Custom'
        md_bg_color:.5,.5,.5,.5
        on_release:self.parent.parent.parent.parent.remove_product(root.nom_produit)
