<SalesPage>:
    orientation: "horizontal"
    size_hint_y: None
    height: self.minimum_height
    MDBoxLayout:
        orientation: "vertical"
        adaptive_height: True
        padding: dp(20)
        spacing: dp(10)
        MDBoxLayout:
            size_hint_y: None
            height: dp(70)
            orientation: "vertical"
            MDLabel:
                id:sale_label1
                text: "Bienvenue."
                halign: "left"
                theme_text_color: "Primary"
                font_style: "Headline"
            MDLabel:
                id:sale_label2
                text: "Vos statistiques d'aujourd'hui"
                halign: "left"
                theme_text_color: "Custom"
                text_color: 2/255, 2/255, 88/255, 1
                font_style: "Headline"

        MDGridLayout:
            id:sale_number
            cols: 3
            spacing: dp(10)
            adaptive_height: True
            padding: dp(10)

            canvas.before:
                Color:
                    rgba: 1, 1, 1, 1
                RoundedRectangle:
                    radius: [20, 20, 20, 20]
                    source: "images/dash.jpg"
                    pos: self.pos
                    size: self.size

            # Cartes de statistiques
            MDCard:
                size_hint_x: 0.30
                adaptive_height: True
                style: "elevated"
                md_bg_color: 1, 1, 1, 1
                radius: [20]
                BoxLayout:
                    orientation: 'vertical'
                    padding: dp(10)
                    spacing: dp(10)
                    MDListItem:
                        md_bg_color: 0.831, 0.855, 0.918, 1
                        size_hint_y: None
                        height: dp(56)
                        MDListItemLeadingIcon:
                            icon: "cash"
                            icon_color: 245/255, 189/255, 32/255, 1
                        MDListItemHeadlineText:
                            text: "somme total gagnée"
                            text_color: 245/255, 189/255, 32/255, 1
                    Label:
                        text: root.somme_nette_totale_gagnee
                        color: 0, .65, 0, 1
                        size_hint_y: None
                        height: self.texture_size[1]

            MDCard:
                size_hint_x: 0.30
                adaptive_height: True
                style: "elevated"
                md_bg_color: 1, 1, 1, 1
                radius: [20]
                BoxLayout:
                    orientation: 'vertical'
                    padding: dp(10)
                    spacing: dp(10)
                    MDListItem:
                        md_bg_color: 0.831, 0.855, 0.918, 1
                        size_hint_y: None
                        height: dp(56)
                        MDListItemLeadingIcon:
                            icon: "sale"
                            icon_color: 245/255, 189/255, 32/255, 1
                        MDListItemHeadlineText:
                            text: "total de ventes"
                            text_color: 245/255, 189/255, 32/255, 1
                    Label:
                        text: root.total_de_ventes
                        color: 0, 0, 0, 1
                        size_hint_y: None
                        height: self.texture_size[1]

            MDCard:
                size_hint_x: 0.26
                adaptive_height: True
                style: "elevated"
                md_bg_color: 212/255, 218/255, 234/255, 1
                radius: [20]
                BoxLayout:
                    orientation: 'vertical'
                    padding: dp(10)
                    spacing: dp(10)
                    MDListItem:
                        md_bg_color: 0.831, 0.855, 0.918, 1
                        size_hint_y: None
                        height: dp(56)
                        MDListItemLeadingIcon:
                            icon: "package-variant"
                            icon_color: 245/255, 189/255, 32/255, 1
                        MDListItemHeadlineText:
                            text: "Produits en rupture"
                            text_color: 245/255, 189/255, 32/255, 1
                    Label:
                        text: root.produits_en_rupture
                        color: .1, 0, 0, 1
                        size_hint_y: None
                        height: self.texture_size[1]

        StatDeVente:
            id: statedevente
            size_hint_y: None
            height: dp(400)
            style: "elevated"
            md_bg_color: 1, 1, 1, 1
            radius: [20]
            on_parent: self.show_stat_du_jour()

    MDBoxLayout:
        id: sale_section_2
        orientation: "vertical"
        size_hint_x: 0.4
        spacing: dp(20)
        padding: dp(20)
        adaptive_height: True

        MDCard:
            style: "elevated"
            md_bg_color: 168/255, 205/255, 230/255, 1
            radius: [20]
            elevation: 10
            size_hint_y: None
            height: dp(300)
            BoxLayout:
                orientation: 'vertical'
                MDListItem:
                    md_bg_color: 186/255, 169/255, 155/255, 1
                    size_hint_y: None
                    height: dp(56)
                    MDListItemLeadingIcon:
                        icon: "sale"
                    MDListItemHeadlineText:
                        text: "liste des ventes"
                ListeVente:
                    id:listevente
                    size_hint_y: 1
                    on_parent: self.show_products_sale()

        MDCard:
            style: "elevated"
            md_bg_color: 168/255, 205/255, 230/255, 1
            radius: [20]
            elevation: 10
            size_hint_y: None
            height: dp(300)
            BoxLayout:
                orientation: 'vertical'
                MDListItem:
                    md_bg_color: 186/255, 169/255, 155/255, 1
                    size_hint_y: None
                    height: dp(56)
                    MDListItemLeadingIcon:
                        icon: "sale"
                    MDListItemHeadlineText:
                        text: "pourcentage de vente des produits"
                PourcentagePV:
                    id: pourcentagepv
                    size_hint_y: 1
                    on_parent: self.show_pourcentage_pv()
