#:import components components.components

<StatsPage>:
    MDBoxLayout:
        adaptive_height: True
        orientation:"vertical"
        padding: dp(20)  # marge autour des enfants
        spacing: dp(10)  # espace entre enfants
        MDBoxLayout:
            size_hint_y: None
            height: dp(70)
            spacing:dp(7)
            padding:dp(7)
            MDButton:
                id:date_button
                theme_bg_color:"Custom"
                md_bg_color:171/255,219/255,227/255,1
                radius:[15]
                size_hint_y: None
                on_release:
                    root.show_date_picker()
                MDButtonText:
                    text:"Date"

            MDButton:
                theme_bg_color:"Custom"
                md_bg_color:171/255,219/255,227/255,1
                radius:[15]
                size_hint_y: None
                on_release:
                    root.show_modal_date_picker()
                MDButtonText:
                    text:"Période"

            MDButton:
                theme_bg_color:"Custom"
                md_bg_color:171/255,219/255,227/255,1
                radius:[15]
                size_hint_y: None
                on_release:
                    root.show_month_picker()
                MDButtonText:
                    text:"Mois"
            MDButton:
                theme_bg_color:"Custom"
                md_bg_color:171/255,219/255,227/255,1
                radius:[15]
                size_hint_y: None
                on_release:
                    root.show_year_picker()
                MDButtonText:
                    text:"Année"
        MDBoxLayout:
            padding: dp(20)
            spacing:dp(20)
            adaptive_height: True
            orientation:"horizontal"

            canvas.before:
                Color:
                    rgba: 1, 1, 1, 1
                RoundedRectangle:
                    radius: [20,20,20,20]
                    source: "images/dash.jpg"
                    pos: self.pos
                    size: self.size
            MDCard:
                adaptive_height: True
                style: "elevated"
                theme_bg_color: "Custom"
                md_bg_color:1,1,1,1
                size_hint_x:0.30
                radius: [20, 20, 20, 20]
                elevation:10
                BoxLayout:
                    adaptive_height: True
                    orientation:'vertical'
                    MDListItem:
                        theme_bg_color: "Custom"
                        md_bg_color: 0.831, 0.855, 0.918, 1  # Equivalent to 212, 218, 234
                        size_hint_y: None
                        height: dp(56)
                        radius:[20]
                        spacing:dp(10)
                        padding:dp(10)
                        pos_hint: {"y": 0.6}
                        halign:"center"

                        MDListItemLeadingIcon:
                            icon: "cash"
                            icon_color:245/255,189/255,32/255,1

                        MDListItemHeadlineText:
                            text: "somme total gagnée"
                            text_color:245/255,189/255,32/255,1
                    Label:
                        id:somme
                        size_hint_y: None
                        height: dp(56)
                        text:root.somme_total_gagnee
                        color:0,.65,0,1
            MDCard:
                adaptive_height: True
                style: "elevated"
                theme_bg_color: "Custom"
                size_hint_x:0.30
                radius: [20, 20, 20, 20]
                elevation:10
                md_bg_color:1,1,1,1
                BoxLayout:
                    adaptive_height: True
                    orientation:'vertical'
                    MDListItem:
                        theme_bg_color: "Custom"
                        md_bg_color: 0.831, 0.855, 0.918, 1  # Equivalent to 212, 218, 234
                        size_hint_y: None
                        height: dp(56)
                        radius:[20]
                        spacing:dp(10)
                        padding:dp(10)
                        pos_hint: {"y": 0.6}
                        halign:"center"

                        MDListItemLeadingIcon:
                            icon: "sale"
                            icon_color:245/255,189/255,32/255,1

                        MDListItemHeadlineText:
                            text: "total de ventes"
                            text_color:245/255,189/255,32/255,1
                    Label:
                        size_hint_y: None
                        height: dp(56)
                        text:root.total_de_ventes
                        color:0,0,0,1

            MDCard:
                adaptive_height: True
                style: "elevated"
                theme_bg_color: "Custom"
                size_hint_x:0.26
                radius: [20, 20, 20, 20]
                elevation:10
                md_bg_color:212/255,218/255,234/255,1
                BoxLayout:
                    adaptive_height: True
                    orientation:'vertical'
                    MDListItem:
                        theme_bg_color: "Custom"
                        md_bg_color: 0.831, 0.855, 0.918, 1  # Equivalent to 212, 218, 234
                        size_hint_y: None
                        height: dp(56)
                        radius:[20]
                        spacing:dp(10)
                        padding:dp(10)
                        pos_hint: {"y": 0.6}
                        halign:"center"

                        MDListItemLeadingIcon:
                            icon: "package-variant"
                            icon_color:245/255,189/255,32/255,1

                        MDListItemHeadlineText:
                            text: "Total de depenses"
                            text_color:245/255,189/255,32/255,1
                    Label:
                        size_hint_y: None
                        height: dp(56)
                        text:root.produits_en_rupture
                        color: .1,0,0,1

        StatDeVenteGlobal:
            id:statedeventeglobal
            style: "elevated"
            theme_bg_color: "Custom"
            size_hint_y: None
            height: dp(400)
            size_hint_x:1
            radius:[20]
            md_bg_color:1,1,1,1
            on_parent:self.show_stat_global()


    MDBoxLayout:
        id:stat_section_2
        adaptive_height: True
        orientation:"vertical"
        size_hint_x: 0.65
        spacing: dp(20)
        padding: dp(20)
        CCard:
            size_hint_y: None
            height: dp(100)
            id:avg_gain
            theme_bg_color: "Custom"
            md_bg_color: 6/255,57/255,112/255,1
            CLabel:
                text:root.avg_gain
        CCard:
            id:avg_dep
            size_hint_y: None
            height: dp(100)
            theme_bg_color: "Custom"
            md_bg_color: 30/255,129/255,176/255,1
            CLabel:
                text:root.avg_dep

        CCard:
            size_hint_y: None
            height: dp(100)
            theme_bg_color: "Custom"
            md_bg_color: 118/255,181/255,197/255,1
            CLabel:
                text:'test'
        CCard:
            size_hint_y: None
            height: dp(100)
            theme_bg_color: "Custom"
            md_bg_color: 171/255,219/255,227/255,1
            CLabel:
                text:'test'