<WalletPage>
    theme_bg_color:"Custom"
    #md_bg_color:139/255,139/255,139/255,1
    md_bg_color:248/255,247/255,242/255,1
    spacing:dp(20)
    padding:dp(20)
    size_hint_y:None
    height:self.minimum_height
    MDBoxLayout:
        adaptive_height: True
        orientation:"vertical"
        spacing:dp(20)
        padding:dp(20)
        MDBoxLayout:
            size_hint_y: None
            height: dp(70)
            orientation: "vertical"
            spacing:dp(7)
            padding:dp(7)
            MDLabel:
                size_hint_y:0.05
                text:"filtrer par"
                font_style:"Title"
                role:"medium"
            MDBoxLayout:
                size_hint_y: None
                height: dp(70)
                spacing:dp(7)
                padding:dp(7)
                MDButton:
                    id:date_button
                    theme_bg_color:"Custom"
                    md_bg_color:171/255,219/255,227/255,1
                    radius:[15]
                    size_hint_y: None
                    on_release:
                        root.show_date_picker()
                    MDButtonText:
                        text:"Date"

                MDButton:
                    theme_bg_color:"Custom"
                    md_bg_color:171/255,219/255,227/255,1
                    radius:[15]
                    size_hint_y: None
                    on_release:
                        root.show_modal_date_picker()
                    MDButtonText:
                        text:"Période"

                MDButton:
                    theme_bg_color:"Custom"
                    md_bg_color:171/255,219/255,227/255,1
                    radius:[15]
                    size_hint_y: None
                    on_release:
                        root.show_month_picker()
                    MDButtonText:
                        text:"Mois"
                MDButton:
                    theme_bg_color:"Custom"
                    md_bg_color:171/255,219/255,227/255,1
                    radius:[15]
                    size_hint_y: None
                    on_release:
                        root.show_year_picker()
                    MDButtonText:
                        text:"Année"

        MDCard:
            size_hint_x:1
            size_hint_y:None
            height:dp(400)
            style: "elevated"
            elevation:10
            radius:[20]
            Historique:
                id:historique
                size_hint : 1,1
                on_parent:self.show_historique()
    MDBoxLayout:
        adaptive_height: True
        id:wallet_section_2
        orientation:"vertical"
        spacing:dp(20)
        padding:dp(20)
        size_hint_x:0.3
        MDCard:
            pos_hint: {"y": 0.8}
            size_hint_y:None
            height:dp(100)
            style: "elevated"
            elevation:10
            radius:[20]
            theme_bg_color:"Custom"
            md_bg_color:139/255,139/255,139/255,1
            BoxLayout:
                adaptive_height: True
                orientation:'vertical'
                MDListItem:
                    theme_bg_color: "Custom"
                    md_bg_color: 214/255,234/255,93/255,1
                    size_hint: 1,None
                    height:dp(30)
                    radius:[20,20,0,0]
                    spacing:dp(10)
                    padding:dp(10)
                    pos_hint: {"y": 0.9}
                    halign:"center"

                    MDListItemLeadingIcon:
                        icon: "currency-usd"


                    MDListItemHeadlineText:

                        text: "somme dans le portefeuille"
                LabelSommePortefeuille:
                    size_hint: 1,None
                    height:dp(70)
                    id:labelsommeportefeuille2
                    text:self.somme_portefeuille
        MDCard:
            size_hint_y:None
            height:dp(300)
            style: "elevated"
            elevation:10
            radius:[20]
            pos_hint: {"y": 0.4}
            MDBoxLayout:
                height:dp(300)
                orientation:"vertical"
                spacing:"20dp"
                MDListItem:
                    theme_bg_color: "Custom"
                    size_hint: 1,None
                    height:dp(30)
                    radius:[20,20,0,0]
                    spacing:dp(10)
                    padding:dp(10)
                    pos_hint: {"y": 0.9}
                    halign:"center"
                    md_bg_color: 139/255,139/255,139/255,1

                    MDListItemLeadingIcon:
                        icon: "swap-horizontal-bold"
                        icon_color:1,1,1,1

                    MDListItemHeadlineText:
                        theme_text_color: "Custom"
                        text_color:1,1,1,1
                        text: "effectuer une Transaction"

                MDTextField:
                    pos_hint:{"center_x": .5}
                    size_hint:.7,None
                    height:dp(40)
                    id:somme_transaction
                    mode:"filled"
                    MDTextFieldHelperText:
                        text:"ex: 8000"
                    MDTextFieldHintText:
                        text:"entrez la somme"

                MDButton:
                    pos_hint: {"center_x": 0.5}
                    size_hint_y:None
                    height:dp(40)
                    style: "filled"
                    on_press:root.add()
                    MDButtonIcon:
                        icon: "check-underline-circle"
                    MDButtonText:
                        text: "effectuer la transaction"

